/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DateText = IDL.Text;
export const WorkerId = IDL.Nat;
export const Worker = IDL.Record({
  'id' : WorkerId,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'joiningDate' : DateText,
  'uniqueId' : IDL.Text,
  'photo' : IDL.Opt(IDL.Text),
});
export const AttendanceStatus = IDL.Variant({
  'onLeave' : IDL.Null,
  'halfDay' : IDL.Null,
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'status' : AttendanceStatus,
  'workerId' : WorkerId,
  'date' : DateText,
  'timestamp' : IDL.Nat,
  'remarks' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserSettings = IDL.Record({ 'darkMode' : IDL.Bool });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWorker' : IDL.Func(
      [IDL.Text, DateText, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Worker],
      [],
    ),
  'deleteWorker' : IDL.Func([WorkerId], [], []),
  'getAllAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDateAttendance' : IDL.Func(
      [DateText],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
  'getWorkerAttendance' : IDL.Func(
      [WorkerId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getWorkerMonthlyAttendance' : IDL.Func(
      [WorkerId, DateText, DateText],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getWorkerMonthlyPresent' : IDL.Func(
      [WorkerId, DateText, DateText],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Nat, WorkerId, AttendanceStatus, DateText, IDL.Opt(IDL.Text)],
      [AttendanceRecord],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserSettings' : IDL.Func([IDL.Bool], [], []),
  'updateWorkerPhoto' : IDL.Func([WorkerId, IDL.Opt(IDL.Text)], [Worker], []),
  'updateWorkerRoleWithDate' : IDL.Func(
      [WorkerId, IDL.Text, IDL.Text],
      [Worker],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DateText = IDL.Text;
  const WorkerId = IDL.Nat;
  const Worker = IDL.Record({
    'id' : WorkerId,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'joiningDate' : DateText,
    'uniqueId' : IDL.Text,
    'photo' : IDL.Opt(IDL.Text),
  });
  const AttendanceStatus = IDL.Variant({
    'onLeave' : IDL.Null,
    'halfDay' : IDL.Null,
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'status' : AttendanceStatus,
    'workerId' : WorkerId,
    'date' : DateText,
    'timestamp' : IDL.Nat,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserSettings = IDL.Record({ 'darkMode' : IDL.Bool });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWorker' : IDL.Func(
        [IDL.Text, DateText, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Worker],
        [],
      ),
    'deleteWorker' : IDL.Func([WorkerId], [], []),
    'getAllAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDateAttendance' : IDL.Func(
        [DateText],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'getWorker' : IDL.Func([WorkerId], [Worker], ['query']),
    'getWorkerAttendance' : IDL.Func(
        [WorkerId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getWorkerMonthlyAttendance' : IDL.Func(
        [WorkerId, DateText, DateText],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getWorkerMonthlyPresent' : IDL.Func(
        [WorkerId, DateText, DateText],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Nat, WorkerId, AttendanceStatus, DateText, IDL.Opt(IDL.Text)],
        [AttendanceRecord],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserSettings' : IDL.Func([IDL.Bool], [], []),
    'updateWorkerPhoto' : IDL.Func([WorkerId, IDL.Opt(IDL.Text)], [Worker], []),
    'updateWorkerRoleWithDate' : IDL.Func(
        [WorkerId, IDL.Text, IDL.Text],
        [Worker],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };