/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'status' : AttendanceStatus,
  'workerId' : WorkerId,
  'date' : DateText,
  'timestamp' : bigint,
  'remarks' : [] | [string],
}
export type AttendanceStatus = { 'onLeave' : null } |
  { 'halfDay' : null } |
  { 'present' : null } |
  { 'absent' : null };
export type DateText = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettings { 'darkMode' : boolean }
export interface Worker {
  'id' : WorkerId,
  'name' : string,
  'role' : string,
  'joiningDate' : DateText,
  'uniqueId' : string,
  'photo' : [] | [string],
}
export type WorkerId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWorker' : ActorMethod<
    [string, DateText, string, string, [] | [string]],
    Worker
  >,
  'deleteWorker' : ActorMethod<[WorkerId], undefined>,
  'getAllAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllWorkers' : ActorMethod<[], Array<Worker>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDateAttendance' : ActorMethod<[DateText], Array<AttendanceRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'getWorker' : ActorMethod<[WorkerId], Worker>,
  'getWorkerAttendance' : ActorMethod<[WorkerId], Array<AttendanceRecord>>,
  'getWorkerMonthlyAttendance' : ActorMethod<
    [WorkerId, DateText, DateText],
    Array<AttendanceRecord>
  >,
  'getWorkerMonthlyPresent' : ActorMethod<
    [WorkerId, DateText, DateText],
    Array<AttendanceRecord>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [bigint, WorkerId, AttendanceStatus, DateText, [] | [string]],
    AttendanceRecord
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserSettings' : ActorMethod<[boolean], undefined>,
  'updateWorkerPhoto' : ActorMethod<[WorkerId, [] | [string]], Worker>,
  'updateWorkerRoleWithDate' : ActorMethod<[WorkerId, string, string], Worker>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];